### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by jpmeijers** [rayozzie/ttn-resin-gateway-rpi#1]
Is there a way we can monitor the temperature (and similar stats) of the gateway? Maybe just run a munin-node on the Pi.

Currently I have a Raspberry Pi 3 and IMST board on the roof in a watertight container. For some reason the gateway disconnected a few hours ago, and now we are wondering if it overheated, or what the reason could be. Of course we are going up the roof tomorrow to open the box, which is quite a bit of work, but it would have been nice to have some hints beforehand.

**Comment by rayozzie** [comment]
good question.  The reality is that i copy the body of the code for this gateway from @gonzalocasas, and so if he implements it in his script and code, i will inherit it here.  I'd suggest pinging him and brainstorming.
