### ISSUE TITLE
Gateway Connector

### ISSUE THREAD

**Issue by jpmeijers** [rayozzie/ttn-resin-gateway-rpi#2]
Any chance we can update this repository with the new packet forwarder/gateway connector:
https://github.com/kersing/packet_forwarder/tree/master/mp_pkt_fwd

**Comment by rayozzie** [comment]
I've been waiting for @gonzalocasas to update his install script, which I will then derive for my resin.io deployment of same. Looking fwd to it.

**Comment by jpmeijers** [comment]
You might want to keep an eye on this one then:
https://github.com/ttn-zh/ic880a-gateway/issues/12

**Comment by jpmeijers** [comment]
I'm done porting the gateway connector software to resin.io. I am however waiting for the gateway connector to be officially released before filing a pull request. This also gives people the possibility to still use the old packet forwarder for now.

https://github.com/jpmeijers/ttn-resin-gateway-rpi
